SET FOREIGN_KEY_CHECKS = 0;
DELETE FROM user_filters;
DELETE FROM location_filters;
DELETE FROM event_filters;
SET FOREIGN_KEY_CHECKS = 1;

-- LOCATIONS UPDATES (Addresses)
UPDATE locations SET country = 'Romania', state_county = 'Iasi', city = 'Iasi', street = 'Strada Viper Club', formatted_address = 'Viper Club, Iasi, Romania' WHERE id = 10;
UPDATE locations SET country = 'Romania', state_county = 'Iasi', city = 'Iasi', street = 'Strada Time Out', formatted_address = 'Time Out, Iasi, Romania' WHERE id = 11;
UPDATE locations SET country = 'Romania', state_county = 'Iasi', city = 'Iasi', street = 'Strada Zona de Agrement Ciric', formatted_address = 'Zona de Agrement Ciric, Iasi, Romania' WHERE id = 12;
UPDATE locations SET country = 'Romania', state_county = 'Iasi', city = 'Iasi', street = 'Strada Cafeneaua Acaju', formatted_address = 'Cafeneaua Acaju, Iasi, Romania' WHERE id = 13;
UPDATE locations SET country = 'Romania', state_county = 'Iasi', city = 'Iasi', street = 'Strada Palas Mall', formatted_address = 'Palas Mall, Iasi, Romania' WHERE id = 14;
UPDATE locations SET country = 'Romania', state_county = 'Iasi', city = 'Iasi', street = 'Strada Teatrul National', formatted_address = 'Teatrul National, Iasi, Romania' WHERE id = 15;
UPDATE locations SET country = 'Romania', state_county = 'Iasi', city = 'Iasi', street = 'Strada Sala Polivalenta', formatted_address = 'Sala Polivalenta, Iasi, Romania' WHERE id = 16;
UPDATE locations SET country = 'Romania', state_county = 'Iasi', city = 'Iasi', street = 'Strada Tiki Village', formatted_address = 'Tiki Village, Iasi, Romania' WHERE id = 17;
UPDATE locations SET country = 'Romania', state_county = 'Iasi', city = 'Iasi', street = 'Strada Gradina Botanica', formatted_address = 'Gradina Botanica, Iasi, Romania' WHERE id = 18;
UPDATE locations SET country = 'Romania', state_county = 'Iasi', city = 'Iasi', street = 'Strada Parcul Copou', formatted_address = 'Parcul Copou, Iasi, Romania' WHERE id = 19;
UPDATE locations SET country = 'Romania', state_county = 'Iasi', city = 'Iasi', street = 'Strada Jassyro', formatted_address = 'Jassyro, Iasi, Romania' WHERE id = 20;
UPDATE locations SET country = 'Romania', state_county = 'Iasi', city = 'Iasi', street = 'Strada Cuib', formatted_address = 'Cuib, Iasi, Romania' WHERE id = 21;
UPDATE locations SET country = 'Romania', state_county = 'Iasi', city = 'Iasi', street = 'Strada Mamma Mia', formatted_address = 'Mamma Mia, Iasi, Romania' WHERE id = 22;
UPDATE locations SET country = 'Romania', state_county = 'Iasi', city = 'Iasi', street = 'Strada Legend Pub', formatted_address = 'Legend Pub, Iasi, Romania' WHERE id = 23;
UPDATE locations SET country = 'Romania', state_county = 'Iasi', city = 'Iasi', street = 'Strada Stadionul Emil Alexandrescu', formatted_address = 'Stadionul Emil Alexandrescu, Iasi, Romania' WHERE id = 24;
UPDATE locations SET country = 'Romania', state_county = 'Iasi', city = 'Iasi', street = 'Strada Tucano Coffee', formatted_address = 'Tucano Coffee, Iasi, Romania' WHERE id = 25;

-- LOCATION FILTERS
INSERT INTO location_filters (location_id, filter_id) VALUES (10, 147);
INSERT INTO location_filters (location_id, filter_id) VALUES (10, 75);
INSERT INTO location_filters (location_id, filter_id) VALUES (10, 85);
INSERT INTO location_filters (location_id, filter_id) VALUES (10, 163);
INSERT INTO location_filters (location_id, filter_id) VALUES (11, 171);
INSERT INTO location_filters (location_id, filter_id) VALUES (11, 85);
INSERT INTO location_filters (location_id, filter_id) VALUES (11, 27);
INSERT INTO location_filters (location_id, filter_id) VALUES (11, 193);
INSERT INTO location_filters (location_id, filter_id) VALUES (12, 159);
INSERT INTO location_filters (location_id, filter_id) VALUES (12, 156);
INSERT INTO location_filters (location_id, filter_id) VALUES (12, 145);
INSERT INTO location_filters (location_id, filter_id) VALUES (12, 164);
INSERT INTO location_filters (location_id, filter_id) VALUES (13, 46);
INSERT INTO location_filters (location_id, filter_id) VALUES (13, 61);
INSERT INTO location_filters (location_id, filter_id) VALUES (13, 85);
INSERT INTO location_filters (location_id, filter_id) VALUES (13, 101);
INSERT INTO location_filters (location_id, filter_id) VALUES (14, 184);
INSERT INTO location_filters (location_id, filter_id) VALUES (14, 183);
INSERT INTO location_filters (location_id, filter_id) VALUES (14, 95);
INSERT INTO location_filters (location_id, filter_id) VALUES (14, 118);
INSERT INTO location_filters (location_id, filter_id) VALUES (15, 210);
INSERT INTO location_filters (location_id, filter_id) VALUES (15, 13);
INSERT INTO location_filters (location_id, filter_id) VALUES (15, 118);
INSERT INTO location_filters (location_id, filter_id) VALUES (16, 194);
INSERT INTO location_filters (location_id, filter_id) VALUES (16, 192);
INSERT INTO location_filters (location_id, filter_id) VALUES (16, 64);
INSERT INTO location_filters (location_id, filter_id) VALUES (16, 118);
INSERT INTO location_filters (location_id, filter_id) VALUES (17, 24);
INSERT INTO location_filters (location_id, filter_id) VALUES (17, 25);
INSERT INTO location_filters (location_id, filter_id) VALUES (17, 163);
INSERT INTO location_filters (location_id, filter_id) VALUES (17, 156);
INSERT INTO location_filters (location_id, filter_id) VALUES (18, 37);
INSERT INTO location_filters (location_id, filter_id) VALUES (18, 156);
INSERT INTO location_filters (location_id, filter_id) VALUES (18, 159);
INSERT INTO location_filters (location_id, filter_id) VALUES (19, 159);
INSERT INTO location_filters (location_id, filter_id) VALUES (19, 156);
INSERT INTO location_filters (location_id, filter_id) VALUES (19, 145);
INSERT INTO location_filters (location_id, filter_id) VALUES (19, 164);
INSERT INTO location_filters (location_id, filter_id) VALUES (20, 62);
INSERT INTO location_filters (location_id, filter_id) VALUES (20, 61);
INSERT INTO location_filters (location_id, filter_id) VALUES (20, 46);
INSERT INTO location_filters (location_id, filter_id) VALUES (20, 85);
INSERT INTO location_filters (location_id, filter_id) VALUES (21, 216);
INSERT INTO location_filters (location_id, filter_id) VALUES (21, 217);
INSERT INTO location_filters (location_id, filter_id) VALUES (21, 175);
INSERT INTO location_filters (location_id, filter_id) VALUES (21, 95);
INSERT INTO location_filters (location_id, filter_id) VALUES (22, 175);
INSERT INTO location_filters (location_id, filter_id) VALUES (22, 167);
INSERT INTO location_filters (location_id, filter_id) VALUES (22, 95);
INSERT INTO location_filters (location_id, filter_id) VALUES (22, 77);
INSERT INTO location_filters (location_id, filter_id) VALUES (23, 171);
INSERT INTO location_filters (location_id, filter_id) VALUES (23, 85);
INSERT INTO location_filters (location_id, filter_id) VALUES (23, 27);
INSERT INTO location_filters (location_id, filter_id) VALUES (23, 134);
INSERT INTO location_filters (location_id, filter_id) VALUES (24, 195);
INSERT INTO location_filters (location_id, filter_id) VALUES (24, 192);
INSERT INTO location_filters (location_id, filter_id) VALUES (24, 98);
INSERT INTO location_filters (location_id, filter_id) VALUES (24, 156);
INSERT INTO location_filters (location_id, filter_id) VALUES (25, 62);
INSERT INTO location_filters (location_id, filter_id) VALUES (25, 61);
INSERT INTO location_filters (location_id, filter_id) VALUES (25, 46);
INSERT INTO location_filters (location_id, filter_id) VALUES (25, 101);

-- EVENT FILTERS
INSERT INTO event_filters (event_id, filter_id) VALUES (10, 61);
INSERT INTO event_filters (event_id, filter_id) VALUES (10, 46);
INSERT INTO event_filters (event_id, filter_id) VALUES (10, 85);
INSERT INTO event_filters (event_id, filter_id) VALUES (11, 61);
INSERT INTO event_filters (event_id, filter_id) VALUES (11, 35);
INSERT INTO event_filters (event_id, filter_id) VALUES (11, 46);
INSERT INTO event_filters (event_id, filter_id) VALUES (12, 78);
INSERT INTO event_filters (event_id, filter_id) VALUES (12, 61);
INSERT INTO event_filters (event_id, filter_id) VALUES (12, 95);
INSERT INTO event_filters (event_id, filter_id) VALUES (13, 146);
INSERT INTO event_filters (event_id, filter_id) VALUES (13, 61);
INSERT INTO event_filters (event_id, filter_id) VALUES (13, 46);
INSERT INTO event_filters (event_id, filter_id) VALUES (14, 33);
INSERT INTO event_filters (event_id, filter_id) VALUES (14, 61);
INSERT INTO event_filters (event_id, filter_id) VALUES (14, 103);
INSERT INTO event_filters (event_id, filter_id) VALUES (15, 178);
INSERT INTO event_filters (event_id, filter_id) VALUES (15, 175);
INSERT INTO event_filters (event_id, filter_id) VALUES (15, 95);
INSERT INTO event_filters (event_id, filter_id) VALUES (16, 121);
INSERT INTO event_filters (event_id, filter_id) VALUES (16, 182);
INSERT INTO event_filters (event_id, filter_id) VALUES (16, 175);
INSERT INTO event_filters (event_id, filter_id) VALUES (16, 95);
INSERT INTO event_filters (event_id, filter_id) VALUES (17, 216);
INSERT INTO event_filters (event_id, filter_id) VALUES (17, 217);
INSERT INTO event_filters (event_id, filter_id) VALUES (17, 95);
INSERT INTO event_filters (event_id, filter_id) VALUES (18, 41);
INSERT INTO event_filters (event_id, filter_id) VALUES (18, 95);
INSERT INTO event_filters (event_id, filter_id) VALUES (19, 120);
INSERT INTO event_filters (event_id, filter_id) VALUES (19, 175);
INSERT INTO event_filters (event_id, filter_id) VALUES (19, 95);
INSERT INTO event_filters (event_id, filter_id) VALUES (20, 167);
INSERT INTO event_filters (event_id, filter_id) VALUES (20, 94);
INSERT INTO event_filters (event_id, filter_id) VALUES (20, 95);
INSERT INTO event_filters (event_id, filter_id) VALUES (21, 44);
INSERT INTO event_filters (event_id, filter_id) VALUES (21, 64);
INSERT INTO event_filters (event_id, filter_id) VALUES (21, 93);
INSERT INTO event_filters (event_id, filter_id) VALUES (22, 198);
INSERT INTO event_filters (event_id, filter_id) VALUES (22, 93);
INSERT INTO event_filters (event_id, filter_id) VALUES (22, 95);
INSERT INTO event_filters (event_id, filter_id) VALUES (23, 175);
INSERT INTO event_filters (event_id, filter_id) VALUES (23, 95);
INSERT INTO event_filters (event_id, filter_id) VALUES (23, 179);
INSERT INTO event_filters (event_id, filter_id) VALUES (24, 140);
INSERT INTO event_filters (event_id, filter_id) VALUES (24, 95);
INSERT INTO event_filters (event_id, filter_id) VALUES (25, 134);
INSERT INTO event_filters (event_id, filter_id) VALUES (25, 65);
INSERT INTO event_filters (event_id, filter_id) VALUES (25, 144);
INSERT INTO event_filters (event_id, filter_id) VALUES (26, 173);
INSERT INTO event_filters (event_id, filter_id) VALUES (26, 171);
INSERT INTO event_filters (event_id, filter_id) VALUES (26, 103);
INSERT INTO event_filters (event_id, filter_id) VALUES (27, 76);
INSERT INTO event_filters (event_id, filter_id) VALUES (27, 27);
INSERT INTO event_filters (event_id, filter_id) VALUES (27, 64);
INSERT INTO event_filters (event_id, filter_id) VALUES (28, 134);
INSERT INTO event_filters (event_id, filter_id) VALUES (28, 144);
INSERT INTO event_filters (event_id, filter_id) VALUES (28, 65);
INSERT INTO event_filters (event_id, filter_id) VALUES (29, 123);
INSERT INTO event_filters (event_id, filter_id) VALUES (29, 144);
INSERT INTO event_filters (event_id, filter_id) VALUES (29, 163);
INSERT INTO event_filters (event_id, filter_id) VALUES (30, 163);
INSERT INTO event_filters (event_id, filter_id) VALUES (30, 75);
INSERT INTO event_filters (event_id, filter_id) VALUES (30, 148);
INSERT INTO event_filters (event_id, filter_id) VALUES (31, 24);
INSERT INTO event_filters (event_id, filter_id) VALUES (31, 83);
INSERT INTO event_filters (event_id, filter_id) VALUES (31, 163);
INSERT INTO event_filters (event_id, filter_id) VALUES (31, 75);
INSERT INTO event_filters (event_id, filter_id) VALUES (32, 60);
INSERT INTO event_filters (event_id, filter_id) VALUES (32, 163);
INSERT INTO event_filters (event_id, filter_id) VALUES (32, 85);
INSERT INTO event_filters (event_id, filter_id) VALUES (33, 163);
INSERT INTO event_filters (event_id, filter_id) VALUES (33, 147);
INSERT INTO event_filters (event_id, filter_id) VALUES (33, 75);
INSERT INTO event_filters (event_id, filter_id) VALUES (34, 187);
INSERT INTO event_filters (event_id, filter_id) VALUES (34, 75);
INSERT INTO event_filters (event_id, filter_id) VALUES (34, 163);
INSERT INTO event_filters (event_id, filter_id) VALUES (35, 210);
INSERT INTO event_filters (event_id, filter_id) VALUES (35, 13);
INSERT INTO event_filters (event_id, filter_id) VALUES (36, 14);
INSERT INTO event_filters (event_id, filter_id) VALUES (36, 90);
INSERT INTO event_filters (event_id, filter_id) VALUES (36, 13);
INSERT INTO event_filters (event_id, filter_id) VALUES (37, 88);
INSERT INTO event_filters (event_id, filter_id) VALUES (37, 13);
INSERT INTO event_filters (event_id, filter_id) VALUES (38, 143);
INSERT INTO event_filters (event_id, filter_id) VALUES (38, 13);
INSERT INTO event_filters (event_id, filter_id) VALUES (39, 210);
INSERT INTO event_filters (event_id, filter_id) VALUES (39, 13);
INSERT INTO event_filters (event_id, filter_id) VALUES (40, 234);
INSERT INTO event_filters (event_id, filter_id) VALUES (40, 227);
INSERT INTO event_filters (event_id, filter_id) VALUES (40, 156);
INSERT INTO event_filters (event_id, filter_id) VALUES (41, 166);
INSERT INTO event_filters (event_id, filter_id) VALUES (41, 156);
INSERT INTO event_filters (event_id, filter_id) VALUES (41, 188);
INSERT INTO event_filters (event_id, filter_id) VALUES (42, 164);
INSERT INTO event_filters (event_id, filter_id) VALUES (42, 159);
INSERT INTO event_filters (event_id, filter_id) VALUES (42, 156);
INSERT INTO event_filters (event_id, filter_id) VALUES (43, 37);
INSERT INTO event_filters (event_id, filter_id) VALUES (43, 88);
INSERT INTO event_filters (event_id, filter_id) VALUES (43, 145);
INSERT INTO event_filters (event_id, filter_id) VALUES (44, 35);
INSERT INTO event_filters (event_id, filter_id) VALUES (44, 156);
INSERT INTO event_filters (event_id, filter_id) VALUES (44, 159);
INSERT INTO event_filters (event_id, filter_id) VALUES (45, 183);
INSERT INTO event_filters (event_id, filter_id) VALUES (45, 184);
INSERT INTO event_filters (event_id, filter_id) VALUES (46, 57);
INSERT INTO event_filters (event_id, filter_id) VALUES (46, 118);
INSERT INTO event_filters (event_id, filter_id) VALUES (47, 90);
INSERT INTO event_filters (event_id, filter_id) VALUES (47, 13);
INSERT INTO event_filters (event_id, filter_id) VALUES (48, 103);
INSERT INTO event_filters (event_id, filter_id) VALUES (48, 64);
INSERT INTO event_filters (event_id, filter_id) VALUES (49, 233);
INSERT INTO event_filters (event_id, filter_id) VALUES (49, 125);
INSERT INTO event_filters (event_id, filter_id) VALUES (49, 13);
INSERT INTO event_filters (event_id, filter_id) VALUES (50, 98);
INSERT INTO event_filters (event_id, filter_id) VALUES (50, 195);
INSERT INTO event_filters (event_id, filter_id) VALUES (50, 192);
INSERT INTO event_filters (event_id, filter_id) VALUES (51, 22);
INSERT INTO event_filters (event_id, filter_id) VALUES (51, 194);
INSERT INTO event_filters (event_id, filter_id) VALUES (51, 192);
INSERT INTO event_filters (event_id, filter_id) VALUES (52, 138);
INSERT INTO event_filters (event_id, filter_id) VALUES (52, 64);
INSERT INTO event_filters (event_id, filter_id) VALUES (52, 192);
INSERT INTO event_filters (event_id, filter_id) VALUES (53, 192);
INSERT INTO event_filters (event_id, filter_id) VALUES (53, 156);
INSERT INTO event_filters (event_id, filter_id) VALUES (54, 135);
INSERT INTO event_filters (event_id, filter_id) VALUES (54, 171);
INSERT INTO event_filters (event_id, filter_id) VALUES (54, 192);

-- USER FILTERS
INSERT INTO user_filters (user_id, filter_id) VALUES (1, 111);
INSERT INTO user_filters (user_id, filter_id) VALUES (1, 56);
INSERT INTO user_filters (user_id, filter_id) VALUES (1, 141);
INSERT INTO user_filters (user_id, filter_id) VALUES (1, 193);
INSERT INTO user_filters (user_id, filter_id) VALUES (2, 75);
INSERT INTO user_filters (user_id, filter_id) VALUES (2, 7);
INSERT INTO user_filters (user_id, filter_id) VALUES (2, 175);
INSERT INTO user_filters (user_id, filter_id) VALUES (2, 27);
INSERT INTO user_filters (user_id, filter_id) VALUES (3, 182);
INSERT INTO user_filters (user_id, filter_id) VALUES (3, 14);
INSERT INTO user_filters (user_id, filter_id) VALUES (3, 48);
INSERT INTO user_filters (user_id, filter_id) VALUES (3, 99);